import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import { useGlobalContext } from "./context";
import { Form, Field, useFormik, Formik } from "formik";

export default function Home(props) {
  const router = useRouter();
  const [inputType, setInputType] = useState("password");
  const [resInfo, setResInfo] = useState("");
  const [loading, setLoading] = useState(false);
  const initialValues = {
    email: "",
    password: "",
  };
  let info;
  const onSubmit = async (data) => {
    console.log(data);
    setLoading(true);
    const response = await fetch(
      "https://vitainline.uz/api/v1/auth/signin/admin",
      {
        method: "POST",
        mode: "cors",
        cache: "no-cache",
        credentials: "same-origin",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      }
    );
    setLoading(false);

    info = await response.json();
    if (response.status == 200) {
      window.localStorage.setItem("token", info.token);
      location.pathname = "admin";
    } else {
      setResInfo("Email yoki parol xato qayta urining!");
    }
  };
  setTimeout(() => {
    setResInfo("");
  }, 5000);

  const formik = useFormik({
    onSubmit,
    initialValues,
  });
  return (
    <div className="bg-[#F5FAFB] w-full">
      <Head>
        <title>Vita in line</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex overflow-auto login-page  w-[100vw]">
        <div className="">
          <div className=" w-[250px] lg:w-auto mx-auto relative">
            <span className=" absolute bg-[url('../images/top-left.png')] bg-cover left-[56px] top-[40px] sm:bg-center w-[100px] md:w-[250px] sm:h-[316] h-[125px] md:left-[px] md:top-[0px] bg-no-repeat"></span>
            <span className="absolute bg-[url('../images/top-bottom.png')] left-[250px] top-[300px] bg-cover w-[120px] h-[130px]  lg:left-[56px] lg:top-[323px] bg-no-repeat"></span>
            <span className="absolute bg-[url('../images/middle.png')]  bg-cover w-0 h-[130px] left-5 lg:left-[471px] lg:top-[54px] bg-no-repeat "></span>
            <span className=" absolute  bg-[url('../images/top-right.png')] md:w-0 bg-cover w-[120px] top-[500px]  h-[130px] right-3  lg:top-[32px] bg-no-repeat"></span>
          </div>
          <div className=" bg-[url('../images/young-doctor1.png')] w-0 md:w-[50vw]  bg-cover h-[100vh] mx-auto bg-no-repeat  left-0 bottom-0 "></div>
        </div>

        <div className=" w-[100vw] flex flex-col justify-center items-center">
          <div className="border relative flex items-center justify-center border-[#C5D7D8] rounded-full bg-white w-[123px] h-[123px] mt-[10px] ">
            <span className="bg-[url('../images/Frame.png')] bg-contain w-[90px] h-[85px] bg-no-repeat absolute"></span>
          </div>
          <div className="flex flex-col items-center w-[300px] md:w-[400px] lg:w-[397px] mt-5 ">
            <h2 className="text-[24px] text-center w-[213px] text-[Black] mx-auto font-[500] leading-[38px]">
              Admin <span className="text-[#1BB7B5]"></span>
            </h2>
            <h1 className="z-[3] text-black">{props.locale}</h1>
            <p className="text-center text-red-400 w-[250px] md:w-[350px]  lg:w-[430px]">
              {resInfo}
            </p>
            <Formik onSubmit={onSubmit} initialValues={initialValues}>
              <Form className="w-full flex flex-col ">
                <label
                  htmlFor="email"
                  className="mt-[10px] mb-2 text-[#759495]"
                >
                  Email
                </label>
                <Field
                  name="email"
                  className="border border-[#D7E6E7] rounded-[12px] p-2 dark:bg-white dark:text-black"
                  type="email"
                  autoComplete="off"
                />
                <label
                  htmlFor="password"
                  className="mt-[14px]  mb-2 text-[#759495]"
                >
                  Parol
                </label>
                <div className="border relative border-[#D7E6E7] rounded-[12px]">
                  <Field
                    name="password"
                    type={inputType}
                    minLength={4}
                    className=" w-full p-2 rounded-[12px] dark:bg-white dark:text-black"
                    placeholder="*******"
                    autoComplete="off"
                  />
                  <span
                    onClick={() => {
                      inputType === "password"
                        ? setInputType("text")
                        : setInputType("password");
                    }}
                    className="bg-[url('../images/glass.png')] w-[22px] bg-no-repeat h-[14px] absolute right-4 top-3"
                  ></span>
                </div>
                <button
                  type="submit"
                  className="mt-[24px] transform- py-[13px] bg-gradient-to-t from-[#1BB7B5] to-[#0EC5C9] text-white rounded-[12px]  font-[500] hover:bg-gradient-to-t hover:from-[#0F9694] hover:to-[#0A7476]"
                >
                  Admin panelga kirish
                </button>
              </Form>
            </Formik>
          </div>
        </div>
      </div>
      {loading ? (
        <div className="z-[2] absolute left-0 bottom-0 right-0 top-0 bg-[rgba(0,0,0,0.2)] ">
          <div className="pl1">
            <div className="pl1__a"></div>
            <div className="pl1__b"></div>
            <div className="pl1__c"></div>
          </div>
        </div>
      ) : (
        ""
      )}
    </div>
  );
}
